/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitter/babysitterverify` | `/babysitter/babysitterverify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitter` | `/babysitter`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/components/AdminAddEventScreen` | `/components/AdminAddEventScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/components/nutrienttracker` | `/components/nutrienttracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/babysitters` | `/mom/babysitters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/health` | `/mom/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom` | `/mom`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/profile` | `/mom/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/schedule` | `/mom/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/babysitter/babysitterverify` | `/babysitter/babysitterverify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/babysitter` | `/babysitter`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/components/AdminAddEventScreen` | `/components/AdminAddEventScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/components/nutrienttracker` | `/components/nutrienttracker`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mom/babysitters` | `/mom/babysitters`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mom/health` | `/mom/health`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mom` | `/mom`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mom/profile` | `/mom/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mom/schedule` | `/mom/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/babysitter/babysitterverify${`?${string}` | `#${string}` | ''}` | `/babysitter/babysitterverify${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/babysitter${`?${string}` | `#${string}` | ''}` | `/babysitter${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/components/AdminAddEventScreen${`?${string}` | `#${string}` | ''}` | `/components/AdminAddEventScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/components/nutrienttracker${`?${string}` | `#${string}` | ''}` | `/components/nutrienttracker${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mom/babysitters${`?${string}` | `#${string}` | ''}` | `/mom/babysitters${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mom/health${`?${string}` | `#${string}` | ''}` | `/mom/health${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mom${`?${string}` | `#${string}` | ''}` | `/mom${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mom/profile${`?${string}` | `#${string}` | ''}` | `/mom/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mom/schedule${`?${string}` | `#${string}` | ''}` | `/mom/schedule${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitter/babysitterverify` | `/babysitter/babysitterverify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitter` | `/babysitter`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/components/AdminAddEventScreen` | `/components/AdminAddEventScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/components/nutrienttracker` | `/components/nutrienttracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/babysitters` | `/mom/babysitters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/health` | `/mom/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom` | `/mom`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/profile` | `/mom/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mom/schedule` | `/mom/schedule`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
