/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/nutrienttracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitterverify` | `/babysitterverify`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitters` | `/babysitters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/health` | `/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/nutrienttracker`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/babysitterverify` | `/babysitterverify`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/auth` | `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/babysitters` | `/babysitters`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/health` | `/health`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/nutrienttracker${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/babysitterverify${`?${string}` | `#${string}` | ''}` | `/babysitterverify${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/auth${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/babysitters${`?${string}` | `#${string}` | ''}` | `/babysitters${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/health${`?${string}` | `#${string}` | ''}` | `/health${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/nutrienttracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitterverify` | `/babysitterverify`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/babysitters` | `/babysitters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/health` | `/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
